### ISSUE TITLE
database name shouldnt be hardcoded

### ISSUE THREAD

**Issue by mickaelandrieu** [ndufreche/KissPHP#1]
See https://github.com/ndufreche/KissPHP/blob/master/Sql.php#L18

**Comment by ndious** [comment]
Yes, this framework need a config file ^^

**Comment by mickaelandrieu** [comment]
^^ I'm surprised to see you create your own _PHP_ framework xD

**Comment by ndious** [comment]
PHP is not my preferred language but I know it well :D.

**Comment by ndious** [comment]
Fix into 1b880538b51e9ec72e38b7feecdf29f8f7d9aa2a commit

**Comment by mickaelandrieu** [comment]
thanks @ndufreche

**Comment by ndious** [comment]
Thanks to your issue @mickaelandrieu
