### ISSUE TITLE
Upgrade to PHP7 with no retro compatibility for 5.* versions

### ISSUE THREAD

**Issue by ndious** [ndufreche/KissPHP#4]
Integrate new usages of PHP7

**Comment by ndious** [comment]
@mickaelandrieu do you think is currently available  ?

**Comment by mickaelandrieu** [comment]
@ndufreche PHP7?  Yes :)

**Comment by ndious** [comment]
Cool, then when I have enough test cover I will work on this.

**Comment by ndious** [comment]
it's done
